### PR TITLE
Fix icon for show/hide password toggle - Bug #31

### LINKED ISSUE #31: Fix icon for show/hide password toggle - Bug
* Currently the show/hide password icon does not toggle - even when clicked to show the password, the icon remains the same instead of a crossed eye

image

image

- [ ] Fix the bug by adding toggle icon logic on click events to toggle between show/hide password

### PR DESCRIPTION
**Pull request by anand-nakat**
Fixes #31 
Toggle class name of **i tag** to **fa-eye** & **fa-eye-slash**..

### CODE REVIEW

File: login.php [hunk 1]
```diff
@@ -89,7 +89,7 @@
 					</div>
 					
 					<div class="register-container w-100 mt-4">
-						<button class="register-btn" onclick="window.location.href='signup.php';">
+						<button class="register-btn" onclick="window.location.href='login.php';">
```
Comment (anand-nakat) [inline login.php:92]: Currently as signup page isn't available, I changed it to login.php

**Review by Chintan2108 — APPROVED** [review]

**Comment by Chintan2108** [comment]
give @anand-nakat 5 points
